apiVersion: apps/v1
kind: Deployment
metadata:
  name: bms-app
  namespace: bms-namespace
  labels:
    app: bms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bms
  template:
    metadata:
      labels:
        app: bms
    spec:
      containers:
      - name: chakri-container
        image: chakriamajaladocker/bookmyshow:latest  # âœ… Always tag your image
        ports:
        - containerPort: 3000
