  apiVersion: v1
kind: Service
metadata:
  name: book1-service
  namespace: bms-namespace
  labels:
    app: bms
spec:                 #clusteripthisipetttukovachu
  type: ClusterIP      # âœ… Keep internal service (Ingress already LoadBalancer)
  selector:
    app: bms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

