apiVersion: v1
kind: Service
metadata:
  name: book1-service
  namespace: bms-namespace
  labels:
    app: bms
spec:
  type: ClusterIP
  selector:
    app: bms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
