apiVersion: v1
kind: Service
metadata:
  name: book-service
  namespace: bms-namespace
  labels:
    app: bms
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000 # Replace with the port your app runs on
  selector:
    app: bms
